
version: 2

updates:
  # Configuration for npm
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "dependabot-auto"
      - "temp"
      - "backstage-bump"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@backstage/*"
    open-pull-requests-limit: 1
    