name: Auto approve

on:
  pull_request_target:
    types: [opened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
      with:
        comment: "Dependabot pull requests are auto-closed"
