name: Create PR for backstage.io

on:
  pull_request_target:
    types: [opened, reopened]
    branches: 
      - 'main'

env:
  COMMIT_MSG: "Updated dependencies from backstage-cli versions:bump"  
jobs:
  rectify-backstage-packages:
    runs-on: ubuntu-latest
    if:  ${{ contains(github.event.pull_request.labels.*.name, 'backstage-bump') && (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == 'mhaley37')}}
    steps:       
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}
          submodules: recursive
      - uses: actions/setup-node@v2
        with:   
          node-version: '16'
      - run: npm install -g yarn
        name: Install yarn
      - run: yarn install
        name: Run yarn install
      - name: Update backstage packages
        id: bump
        run: 
        # This may need to be called with yarn.  Also, better to find way to capture full output
          echo "::set-output name=CLI_OUT::$(yarn backstage-cli versions:bump)"
      - name: Update pull request
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          head-branch-regex: ${{github.head_ref}}
          title-template: ${{ env.COMMIT_MSG}}
          title-update-action: replace
          body-template: ${{ steps.bump.outputs.CLI_OUT  }}
          body-update-action: replace
      - name: Commit changes and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add . && git commit -m "${{ env.COMMIT_MSG}}" && git push