name: Create PR for backstage.io

on:
  pull_request_target:
    types: [opened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:       
      - run: echo "Checking out branch $GITHUB_REF named $GITHUB_REF_NAME"
      - run: echo "This is the branch name for the PR, $GITHUB_BASE_REF"
      - uses: actions/checkout@v2
        #with: 
          #ref: github.base_ref
      - uses: actions/setup-node@v2
        with: 
          node-version: '16'
      - run: npm install -g yarn
      #- run: yarn global add backstage-cli
      #- run: yarn backstage-cli versions-bump
      - run: npx backstage-cli versions-bump
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "Dependabot pull requests are auto-closed"
    