name: Create PR for backstage.io

on:
  pull_request_target:
    types: [opened, reopened]
    branches: 
      - 'main'

env:
  COMMIT_MSG: "Updated dependencies from backstage-cli versions:bump"  
jobs:
  rectify-backstage-packages:
    runs-on: ubuntu-latest
    if:  ${{ contains(github.event.pull_request.labels.*.name, 'backstage-bump') && (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' || github.actor == 'mhaley37')}}
    steps:       
      - uses: actions/checkout@v2
        with:
          ref: ${{github.head_ref}}
      - uses: actions/setup-node@v2
        with:   
          node-version: '16'
      - run: npx yarn install
      - name: bump backstage package versions
        id: steps
        run: echo "::set-output name=TAG_NAME::$(backstage-cli versions:bump)"
      - name: update pull request
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          head-branch-regex: ${{github.head_ref}}
          title-template: ${{ env.COMMIT_MSG}}
          body-template: ${{ steps.version.outputs.TAG_NAME  }}
      - name: Commit changes and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add . && git commit -m "${{ env.COMMIT_MSG}}" && git push