name: Auto approve

on:
  pull_request_target:
    types: [opened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:       
      - uses: actions/checkout@2
      - uses: actions/setup-node@v2
        with: 
          node-version: '16'
      - run: npm install -g yarn
      - run: yarn global add backstage-cli
      - run: backstage-cli versions-bump
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "Dependabot pull requests are auto-closed"
    